# Welcome to Serverless!
# Happy Coding!

service: comic-fetcher

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "arn:aws:dynamodb:us-east-1:*:table/comics"
      Action:
        - "dynamodb:*"

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - handler.js
    - services/**
    - node_modules/**
  exclude:
    - tests/**

functions:
  comicFetch:
    handler: handler.checkComics
    events:
          - schedule: cron(10 10 ? * * *)

